export function getFlagLink(country) {
  return `http://purecatamphetamine.github.io/country-flag-icons/3x2/${country}.svg`;
}

export function getCountryList() {
  return [
    {
      value: "Afghanistan",
      display: "countries.Afghanistan",
      symbol: "AF",
      code: "+93",
    },
    {
      value: "Albania",
      display: "countries.Albania",
      symbol: "AL",
      code: "+355",
    },
    {
      value: "Algeria",
      display: "countries.Algeria",
      symbol: "DZ",
      code: "+213",
    },
    {
      value: "Andorra",
      display: "countries.Andorra",
      symbol: "AD",
      code: "+376",
    },
    {
      value: "Angola",
      display: "countries.Angola",
      symbol: "AO",
      code: "+244",
    },
    {
      value: "Anguilla",
      display: "countries.Anguilla",
      symbol: "AI",
      code: "+1-264",
    },
    {
      value: "Antigua & Barbuda",
      display: "countries.AntiguaBarbuda",
      symbol: "AG",
      code: "+1-268",
    },
    {
      value: "Argentina",
      display: "countries.Argentina",
      symbol: "AR",
      code: "+54",
    },
    {
      value: "Armenia",
      display: "countries.Armenia",
      symbol: "AM",
      code: "+374",
    },
    { value: "Aruba", display: "countries.Aruba", symbol: "AW", code: "+297" },
    {
      value: "Australia",
      display: "countries.Australia",
      symbol: "AU",
      code: "+61",
    },
    {
      value: "Austria",
      display: "countries.Austria",
      symbol: "AT",
      code: "+43",
    },
    {
      value: "Azerbaijan",
      display: "countries.Azerbaijan",
      symbol: "AZ",
      code: "+994",
    },
    {
      value: "Bahamas",
      display: "countries.Bahamas",
      symbol: "BS",
      code: "+1-242",
    },
    {
      value: "Bahrain",
      display: "countries.Bahrain",
      symbol: "BH",
      code: "+973",
    },
    {
      value: "Bangladesh",
      display: "countries.Bangladesh",
      symbol: "BD",
      code: "+880",
    },
    {
      value: "Barbados",
      display: "countries.Barbados",
      symbol: "BB",
      code: "+1-246",
    },
    {
      value: "Belarus",
      display: "countries.Belarus",
      symbol: "BY",
      code: "+375",
    },
    {
      value: "Belgium",
      display: "countries.Belgium",
      symbol: "BE",
      code: "+32",
    },
    {
      value: "Belize",
      display: "countries.Belize",
      symbol: "BZ",
      code: "+501",
    },
    { value: "Benin", display: "countries.Benin", symbol: "BJ", code: "+229" },
    {
      value: "Bermuda",
      display: "countries.Bermuda",
      symbol: "BM",
      code: "+1-441",
    },
    {
      value: "Bhutan",
      display: "countries.Bhutan",
      symbol: "BT",
      code: "+975",
    },
    {
      value: "Bolivia",
      display: "countries.Bolivia",
      symbol: "BO",
      code: "+591",
    },
    {
      value: "Bosnia & Herzegovina",
      display: "countries.BosniaHerzegovina",
      symbol: "BA",
      code: "+387",
    },
    {
      value: "Botswana",
      display: "countries.Botswana",
      symbol: "BW",
      code: "+267",
    },
    { value: "Brazil", display: "countries.Brazil", symbol: "BR", code: "+55" },
    {
      value: "British Virgin Islands",
      display: "countries.BritishVirginIslands",
      symbol: "IO",
      code: "+1-284",
    },
    {
      value: "Brunei",
      display: "countries.Brunei",
      symbol: "BN",
      code: "+673",
    },
    {
      value: "Bulgaria",
      display: "countries.Bulgaria",
      symbol: "BG",
      code: "+359",
    },
    {
      value: "Burkina Faso",
      display: "countries.BurkinaFaso",
      symbol: "BF",
      code: "+226",
    },
    {
      value: "Burundi",
      display: "countries.Burundi",
      symbol: "BI",
      code: "+257",
    },
    {
      value: "Cambodia",
      display: "countries.Cambodia",
      symbol: "KH",
      code: "+855",
    },
    {
      value: "Cameroon",
      display: "countries.Cameroon",
      symbol: "CM",
      code: "+237",
    },
    {
      value: "Cape Verde",
      display: "countries.CapeVerde",
      symbol: "CV",
      code: "+238",
    },
    {
      value: "Cayman Islands",
      display: "countries.CaymanIslands",
      symbol: "KY",
      code: "+1-345",
    },
    { value: "Chad", display: "countries.Chad", symbol: "TD", code: "+235" },
    { value: "Chile", display: "countries.Chile", symbol: "CL", code: "+56" },
    { value: "China", display: "countries.China", symbol: "CN", code: "+86" },
    {
      value: "Colombia",
      display: "countries.Colombia",
      symbol: "CO",
      code: "+57",
    },
    { value: "Congo", display: "countries.Congo", symbol: "CG", code: "+242" },
    {
      value: "Cook Islands",
      display: "countries.CookIslands",
      symbol: "CK",
      code: "+682",
    },
    {
      value: "Costa Rica",
      display: "countries.CostaRica",
      symbol: "CR",
      code: "+506",
    },
    {
      value: "Cote D'Ivoire",
      display: "countries.CoteDIvoire",
      symbol: "CI",
      code: "+225",
    },
    {
      value: "Croatia",
      display: "countries.Croatia",
      symbol: "HR",
      code: "+385",
    },
    { value: "Cuba", display: "countries.Cuba", symbol: "CU", code: "+53" },
    {
      value: "Cyprus",
      display: "countries.Cyprus",
      symbol: "CY",
      code: "+357",
    },
    {
      value: "Czech Republic",
      display: "countries.CzechRepublic",
      symbol: "CZ",
      code: "+420",
    },
    {
      value: "Denmark",
      display: "countries.Denmark",
      symbol: "DK",
      code: "+45",
    },
    {
      value: "Djibouti",
      display: "countries.Djibouti",
      symbol: "DJ",
      code: "+253",
    },
    {
      value: "Dominica",
      display: "countries.Dominica",
      symbol: "DM",
      code: "+1-767",
    },
    {
      value: "Dominican Republic",
      display: "countries.DominicanRepublic",
      symbol: "DO",
      code: "+1-809",
    },
    {
      value: "Ecuador",
      display: "countries.Ecuador",
      symbol: "EC",
      code: "+593",
    },
    { value: "Egypt", display: "countries.Egypt", symbol: "EG", code: "+20" },
    {
      value: "El Salvador",
      display: "countries.ElSalvador",
      symbol: "SV",
      code: "+503",
    },
    {
      value: "Equatorial Guinea",
      display: "countries.EquatorialGuinea",
      symbol: "GQ",
      code: "+240",
    },
    {
      value: "Estonia",
      display: "countries.Estonia",
      symbol: "EE",
      code: "+372",
    },
    {
      value: "Ethiopia",
      display: "countries.Ethiopia",
      symbol: "ET",
      code: "+251",
    },
    {
      value: "Falkland Islands",
      display: "countries.FalklandIslands",
      symbol: "FK",
      code: "+500",
    },
    {
      value: "Faroe Islands",
      display: "countries.FaroeIslands",
      symbol: "FO",
      code: "+298",
    },
    { value: "Fiji", display: "countries.Fiji", symbol: "FJ", code: "+679" },
    {
      value: "Finland",
      display: "countries.Finland",
      symbol: "FI",
      code: "+358",
    },
    { value: "France", display: "countries.France", symbol: "FR", code: "+33" },
    {
      value: "French Polynesia",
      display: "countries.FrenchPolynesia",
      symbol: "PF",
      code: "+689",
    },

    { value: "Gabon", display: "countries.Gabon", symbol: "GA", code: "+241" },
    {
      value: "Gambia",
      display: "countries.Gambia",
      symbol: "GM",
      code: "+220",
    },
    {
      value: "Georgia",
      display: "countries.Georgia",
      symbol: "GE",
      code: "+995",
    },
    {
      value: "Germany",
      display: "countries.Germany",
      symbol: "DE",
      code: "+49",
    },
    { value: "Ghana", display: "countries.Ghana", symbol: "GH", code: "+233" },
    {
      value: "Gibraltar",
      display: "countries.Gibraltar",
      symbol: "GI",
      code: "+350",
    },
    { value: "Greece", display: "countries.Greece", symbol: "GR", code: "+30" },
    {
      value: "Greenland",
      display: "countries.Greenland",
      symbol: "GL",
      code: "+299",
    },
    {
      value: "Grenada",
      display: "countries.Grenada",
      symbol: "GD",
      code: "+1-473",
    },
    {
      value: "Guatemala",
      display: "countries.Guatemala",
      symbol: "GT",
      code: "+502",
    },
    {
      value: "Guernsey",
      display: "countries.Guernsey",
      symbol: "GG",
      code: "+44",
    },
    {
      value: "Guinea",
      display: "countries.Guinea",
      symbol: "GN",
      code: "+224",
    },
    {
      value: "Guinea-Bissau",
      display: "countries.GuineaBissau",
      symbol: "GW",
      code: "+245",
    },
    {
      value: "Guyana",
      display: "countries.Guyana",
      symbol: "GY",
      code: "+592",
    },
    { value: "Haiti", display: "countries.Haiti", symbol: "HT", code: "+509" },
    {
      value: "Honduras",
      display: "countries.Honduras",
      symbol: "HN",
      code: "+504",
    },
    {
      value: "Hong Kong",
      display: "countries.HongKong",
      symbol: "HK",
      code: "+852",
    },
    {
      value: "Hungary",
      display: "countries.Hungary",
      symbol: "HU",
      code: "+36",
    },
    {
      value: "Iceland",
      display: "countries.Iceland",
      symbol: "IS",
      code: "+354",
    },
    { value: "India", display: "countries.India", symbol: "IN", code: "+91" },
    {
      value: "Indonesia",
      display: "countries.Indonesia",
      symbol: "ID",
      code: "+62",
    },
    { value: "Iran", display: "countries.Iran", symbol: "IR", code: "+98" },
    { value: "Iraq", display: "countries.Iraq", symbol: "IQ", code: "+964" },
    {
      value: "Ireland",
      display: "countries.Ireland",
      symbol: "IE",
      code: "+353",
    },
    {
      value: "Israel",
      display: "countries.Israel",
      symbol: "IL",
      code: "+972",
    },
    { value: "Italy", display: "countries.Italy", symbol: "IT", code: "+39" },
    {
      value: "Jamaica",
      display: "countries.Jamaica",
      symbol: "JM",
      code: "+1-876",
    },
    { value: "Japan", display: "countries.Japan", symbol: "JP", code: "+81" },
    { value: "Jersey", display: "countries.Jersey", symbol: "JE", code: "+44" },
    {
      value: "Jordan",
      display: "countries.Jordan",
      symbol: "JO",
      code: "+962",
    },
    {
      value: "Kazakhstan",
      display: "countries.Kazakhstan",
      symbol: "KZ",
      code: "+7",
    },
    { value: "Kenya", display: "countries.Kenya", symbol: "KE", code: "+254" },
    {
      value: "Kuwait",
      display: "countries.Kuwait",
      symbol: "KW",
      code: "+965",
    },
    { value: "Laos", display: "countries.Laos", symbol: "LA", code: "+856" },
    {
      value: "Latvia",
      display: "countries.Latvia",
      symbol: "LV",
      code: "+371",
    },
    {
      value: "Lebanon",
      display: "countries.Lebanon",
      symbol: "LB",
      code: "+961",
    },
    {
      value: "Lesotho",
      display: "countries.Lesotho",
      symbol: "LS",
      code: "+266",
    },
    {
      value: "Liberia",
      display: "countries.Liberia",
      symbol: "LR",
      code: "+231",
    },
    { value: "Libya", display: "countries.Libya", symbol: "LY", code: "+218" },
    {
      value: "Liechtenstein",
      display: "countries.Liechtenstein",
      symbol: "LI",
      code: "+423",
    },
    {
      value: "Lithuania",
      display: "countries.Lithuania",
      symbol: "LT",
      code: "+370",
    },
    {
      value: "Luxembourg",
      display: "countries.Luxembourg",
      symbol: "LU",
      code: "+352",
    },
    { value: "Macau", display: "countries.Macau", symbol: "MO", code: "+853" },
    {
      value: "Macedonia",
      display: "countries.Macedonia",
      symbol: "MK",
      code: "+389",
    },
    {
      value: "Madagascar",
      display: "countries.Madagascar",
      symbol: "MG",
      code: "+261",
    },
    {
      value: "Malawi",
      display: "countries.Malawi",
      symbol: "MW",
      code: "+265",
    },
    {
      value: "Malaysia",
      display: "countries.Malaysia",
      symbol: "MY",
      code: "+60",
    },
    {
      value: "Maldives",
      display: "countries.Maldives",
      symbol: "MV",
      code: "+960",
    },
    { value: "Mali", display: "countries.Mali", symbol: "ML", code: "+223" },
    { value: "Malta", display: "countries.Malta", symbol: "MT", code: "+356" },
    {
      value: "Mauritania",
      display: "countries.Mauritania",
      symbol: "MR",
      code: "+222",
    },
    {
      value: "Mauritius",
      display: "countries.Mauritius",
      symbol: "MU",
      code: "+230",
    },
    { value: "Mexico", display: "countries.Mexico", symbol: "MX", code: "+52" },
    {
      value: "Moldova",
      display: "countries.Moldova",
      symbol: "MD",
      code: "+373",
    },
    {
      value: "Monaco",
      display: "countries.Monaco",
      symbol: "MC",
      code: "+377",
    },
    {
      value: "Mongolia",
      display: "countries.Mongolia",
      symbol: "MN",
      code: "+976",
    },
    {
      value: "Montenegro",
      display: "countries.Montenegro",
      symbol: "ME",
      code: "+382",
    },
    {
      value: "Montserrat",
      display: "countries.Montserrat",
      symbol: "MS",
      code: "+1-664",
    },
    {
      value: "Morocco",
      display: "countries.Morocco",
      symbol: "MA",
      code: "+212",
    },
    {
      value: "Mozambique",
      display: "countries.Mozambique",
      symbol: "MZ",
      code: "+258",
    },

    {
      value: "Namibia",
      display: "countries.Namibia",
      symbol: "NA",
      code: "+264",
    },
    { value: "Nepal", display: "countries.Nepal", symbol: "NP", code: "+977" },
    {
      value: "Netherlands",
      display: "countries.Netherlands",
      symbol: "NL",
      code: "+31",
    },
    {
      value: "New Zealand",
      display: "countries.NewZealand",
      symbol: "NZ",
      code: "+64",
    },
    {
      value: "Nicaragua",
      display: "countries.Nicaragua",
      symbol: "NI",
      code: "+505",
    },
    { value: "Niger", display: "countries.Niger", symbol: "NE", code: "+227" },
    {
      value: "Nigeria",
      display: "countries.Nigeria",
      symbol: "NG",
      code: "+234",
    },
    { value: "Norway", display: "countries.Norway", symbol: "NO", code: "+47" },
    { value: "Oman", display: "countries.Oman", symbol: "OM", code: "+968" },
    {
      value: "Pakistan",
      display: "countries.Pakistan",
      symbol: "PK",
      code: "+92",
    },
    {
      value: "Palestine",
      display: "countries.Palestine",
      symbol: "PS",
      code: "+970",
    },
    {
      value: "Panama",
      display: "countries.Panama",
      symbol: "PA",
      code: "+507",
    },
    {
      value: "Papua New Guinea",
      display: "countries.PapuaNewGuinea",
      symbol: "PG",
      code: "+675",
    },
    {
      value: "Paraguay",
      display: "countries.Paraguay",
      symbol: "PY",
      code: "+595",
    },
    { value: "Peru", display: "countries.Peru", symbol: "PE", code: "+51" },
    {
      value: "Philippines",
      display: "countries.Philippines",
      symbol: "PH",
      code: "+63",
    },
    { value: "Poland", display: "countries.Poland", symbol: "PL", code: "+48" },
    {
      value: "Portugal",
      display: "countries.Portugal",
      symbol: "PT",
      code: "+351",
    },
    {
      value: "Puerto Rico",
      display: "countries.PuertoRico",
      symbol: "PR",
      code: "+1-787",
    },
    { value: "Qatar", display: "countries.Qatar", symbol: "QA", code: "+974" },
    {
      value: "Reunion",
      display: "countries.Reunion",
      symbol: "RE",
      code: "+262",
    },
    {
      value: "Romania",
      display: "countries.Romania",
      symbol: "RO",
      code: "+40",
    },
    { value: "Russia", display: "countries.Russia", symbol: "RU", code: "+7" },
    {
      value: "Rwanda",
      display: "countries.Rwanda",
      symbol: "RW",
      code: "+250",
    },
    { value: "Samoa", display: "countries.Samoa", symbol: "WS", code: "+685" },
    {
      value: "San Marino",
      display: "countries.SanMarino",
      symbol: "SM",
      code: "+378",
    },
    {
      value: "Saudi Arabia",
      display: "countries.SaudiArabia",
      symbol: "SA",
      code: "+966",
    },
    {
      value: "Senegal",
      display: "countries.Senegal",
      symbol: "SN",
      code: "+221",
    },
    {
      value: "Serbia",
      display: "countries.Serbia",
      symbol: "RS",
      code: "+381",
    },
    {
      value: "Seychelles",
      display: "countries.Seychelles",
      symbol: "SC",
      code: "+248",
    },
    {
      value: "Sierra Leone",
      display: "countries.SierraLeone",
      symbol: "SL",
      code: "+232",
    },
    {
      value: "Singapore",
      display: "countries.Singapore",
      symbol: "SG",
      code: "+65",
    },
    {
      value: "Slovakia",
      display: "countries.Slovakia",
      symbol: "SK",
      code: "+421",
    },
    {
      value: "Slovenia",
      display: "countries.Slovenia",
      symbol: "SI",
      code: "+386",
    },
    {
      value: "South Africa",
      display: "countries.SouthAfrica",
      symbol: "ZA",
      code: "+27",
    },
    {
      value: "South Korea",
      display: "countries.SouthKorea",
      symbol: "KR",
      code: "+82",
    },
    { value: "Spain", display: "countries.Spain", symbol: "ES", code: "+34" },
    {
      value: "Sri Lanka",
      display: "countries.SriLanka",
      symbol: "LK",
      code: "+94",
    },
    { value: "Sudan", display: "countries.Sudan", symbol: "SD", code: "+249" },
    {
      value: "Suriname",
      display: "countries.Suriname",
      symbol: "SR",
      code: "+597",
    },
    {
      value: "Swaziland",
      display: "countries.Swaziland",
      symbol: "SZ",
      code: "+268",
    },
    { value: "Sweden", display: "countries.Sweden", symbol: "SE", code: "+46" },
    {
      value: "Switzerland",
      display: "countries.Switzerland",
      symbol: "CH",
      code: "+41",
    },
    { value: "Syria", display: "countries.Syria", symbol: "SY", code: "+963" },
    {
      value: "Taiwan",
      display: "countries.Taiwan",
      symbol: "TW",
      code: "+886",
    },
    {
      value: "Tajikistan",
      display: "countries.Tajikistan",
      symbol: "TJ",
      code: "+992",
    },
    {
      value: "Tanzania",
      display: "countries.Tanzania",
      symbol: "TZ",
      code: "+255",
    },
    {
      value: "Thailand",
      display: "countries.Thailand",
      symbol: "TH",
      code: "+66",
    },
    { value: "Togo", display: "countries.Togo", symbol: "TG", code: "+228" },
    { value: "Tonga", display: "countries.Tonga", symbol: "TO", code: "+676" },
    {
      value: "Tunisia",
      display: "countries.Tunisia",
      symbol: "TN",
      code: "+216",
    },
    { value: "Turkey", display: "countries.Turkey", symbol: "TR", code: "+90" },
    {
      value: "Turkmenistan",
      display: "countries.Turkmenistan",
      symbol: "TM",
      code: "+993",
    },
    {
      value: "Uganda",
      display: "countries.Uganda",
      symbol: "UG",
      code: "+256",
    },
    {
      value: "Ukraine",
      display: "countries.Ukraine",
      symbol: "UA",
      code: "+380",
    },
    {
      value: "United Arab Emirates",
      display: "countries.UnitedArabEmirates",
      symbol: "AE",
      code: "+971",
    },
    {
      value: "United Kingdom",
      display: "countries.UnitedKingdom",
      symbol: "GB",
      code: "+44",
    },
    {
      value: "United States",
      display: "countries.unitedStates",
      symbol: "US",
      code: "+1",
    },
    {
      value: "Uruguay",
      display: "countries.Uruguay",
      symbol: "UY",
      code: "+598",
    },
    {
      value: "Uzbekistan",
      display: "countries.Uzbekistan",
      symbol: "UZ",
      code: "+998",
    },
    {
      value: "Venezuela",
      display: "countries.Venezuela",
      symbol: "VE",
      code: "+58",
    },
    {
      value: "Vietnam",
      display: "countries.Vietnam",
      symbol: "VN",
      code: "+84",
    },
    { value: "Yemen", display: "countries.Yemen", symbol: "YE", code: "+967" },
    {
      value: "Zambia",
      display: "countries.Zambia",
      symbol: "ZM",
      code: "+260",
    },
    {
      value: "Zimbabwe",
      display: "countries.Zimbabwe",
      symbol: "ZW",
      code: "+263",
    },
  ].sort((country1, country2) => {
    return country1.value.localeCompare(country2.value);
  });
}

export function getCurrencySymbol() {
  return {
    USD: "$",
    EUR: "€",
    CHF: "CHF",
    UAH: "₴",
    AED: "د.إ",
  };
}

export function getCurrencyFlag() {
  return {
    USD: <img src={getFlagLink("US")} alt="icon" />,
    EUR: <img src={getFlagLink("EU")} alt="icon" />,
    CHF: <img src={getFlagLink("CH")} alt="icon" />,
    UAH: <img src={getFlagLink("UA")} alt="icon" />,
    AED: <img src={getFlagLink("AE")} alt="icon" />,
  };
}
