export function getFlagLink(country) {
  return `http://purecatamphetamine.github.io/country-flag-icons/3x2/${country}.svg`;
}

export function getCountryList() {
  return [
    { value: "Afghanistan", display: "countries.Afghanistan", symbol: "AF" },
    { value: "Albania", display: "countries.Albania", symbol: "AL" },
    { value: "Algeria", display: "countries.Algeria", symbol: "DZ" },
    { value: "Andorra", display: "countries.Andorra", symbol: "AD" },
    { value: "Angola", display: "countries.Angola", symbol: "AO" },
    { value: "Anguilla", display: "countries.Anguilla", symbol: "AI" },
    {
      value: "Antigua & Barbuda",
      display: "countries.AntiguaBarbuda",
      symbol: "AG",
    },
    { value: "Argentina", display: "countries.Argentina", symbol: "AR" },
    { value: "Armenia", display: "countries.Armenia", symbol: "AM" },
    { value: "Aruba", display: "countries.Aruba", symbol: "AW" },
    { value: "Australia", display: "countries.Australia", symbol: "AU" },
    { value: "Austria", display: "countries.Austria", symbol: "AT" },
    { value: "Azerbaijan", display: "countries.Azerbaijan", symbol: "AZ" },
    { value: "Bahamas", display: "countries.Bahamas", symbol: "BS" },
    { value: "Bahrain", display: "countries.Bahrain", symbol: "BH" },
    { value: "Bangladesh", display: "countries.Bangladesh", symbol: "BD" },
    { value: "Barbados", display: "countries.Barbados", symbol: "BB" },
    { value: "Belarus", display: "countries.Belarus", symbol: "BY" },
    { value: "Belgium", display: "countries.Belgium", symbol: "BE" },
    { value: "Belize", display: "countries.Belize", symbol: "BZ" },
    { value: "Benin", display: "countries.Benin", symbol: "BJ" },
    { value: "Bermuda", display: "countries.Bermuda", symbol: "BM" },
    { value: "Bhutan", display: "countries.Bhutan", symbol: "BT" },
    { value: "Bolivia", display: "countries.Bolivia", symbol: "BO" },
    {
      value: "Bosnia & Herzegovina",
      display: "countries.BosniaHerzegovina",
      symbol: "BA",
    },
    { value: "Botswana", display: "countries.Botswana", symbol: "BW" },
    { value: "Brazil", display: "countries.Brazil", symbol: "BR" },
    {
      value: "British Virgin Islands",
      display: "countries.BritishVirginIslands",
      symbol: "IO",
    },
    { value: "Brunei", display: "countries.Brunei", symbol: "BN" },
    { value: "Bulgaria", display: "countries.Bulgaria", symbol: "BG" },
    { value: "Burkina Faso", display: "countries.BurkinaFaso", symbol: "BF" },
    { value: "Burundi", display: "countries.Burundi", symbol: "BI" },
    { value: "Cambodia", display: "countries.Cambodia", symbol: "KH" },
    { value: "Cameroon", display: "countries.Cameroon", symbol: "CM" },
    { value: "Cape Verde", display: "countries.CapeVerde", symbol: "CV" },
    {
      value: "Cayman Islands",
      display: "countries.CaymanIslands",
      symbol: "KY",
    },
    { value: "Chad", display: "countries.Chad", symbol: "TD" },
    { value: "Chile", display: "countries.Chile", symbol: "CL" },
    { value: "China", display: "countries.China", symbol: "CN" },
    { value: "Colombia", display: "countries.Colombia", symbol: "CO" },
    { value: "Congo", display: "countries.Congo", symbol: "CG" },
    { value: "Cook Islands", display: "countries.CookIslands", symbol: "CK" },
    { value: "Costa Rica", display: "countries.CostaRica", symbol: "CR" },
    { value: "Cote D'Ivoire", display: "countries.CoteDIvoire", symbol: "CI" },
    { value: "Croatia", display: "countries.Croatia", symbol: "HR" },
    { value: "Cuba", display: "countries.Cuba", symbol: "CU" },
    { value: "Cyprus", display: "countries.Cyprus", symbol: "CY" },
    {
      value: "Czech Republic",
      display: "countries.CzechRepublic",
      symbol: "CZ",
    },
    { value: "Denmark", display: "countries.Denmark", symbol: "DK" },
    { value: "Djibouti", display: "countries.Djibouti", symbol: "DJ" },
    { value: "Dominica", display: "countries.Dominica", symbol: "DM" },
    {
      value: "Dominican Republic",
      display: "countries.DominicanRepublic",
      symbol: "DO",
    },
    { value: "Ecuador", display: "countries.Ecuador", symbol: "EC" },
    { value: "Egypt", display: "countries.Egypt", symbol: "EG" },
    { value: "El Salvador", display: "countries.ElSalvador", symbol: "SV" },
    {
      value: "Equatorial Guinea",
      display: "countries.EquatorialGuinea",
      symbol: "GQ",
    },
    { value: "Estonia", display: "countries.Estonia", symbol: "EE" },
    { value: "Ethiopia", display: "countries.Ethiopia", symbol: "ET" },
    {
      value: "Falkland Islands",
      display: "countries.FalklandIslands",
      symbol: "FK",
    },
    { value: "Faroe Islands", display: "countries.FaroeIslands", symbol: "FO" },
    { value: "Fiji", display: "countries.Fiji", symbol: "FJ" },
    { value: "Finland", display: "countries.Finland", symbol: "FI" },
    { value: "France", display: "countries.France", symbol: "FR" },
    {
      value: "French Polynesia",
      display: "countries.FrenchPolynesia",
      symbol: "PF",
    },
    {
      value: "French West Indies",
      display: "countries.FrenchWestIndies",
      symbol: "TF",
    },
    { value: "Gabon", display: "countries.Gabon", symbol: "GA" },
    { value: "Gambia", display: "countries.Gambia", symbol: "GM" },
    { value: "Georgia", display: "countries.Georgia", symbol: "GE" },
    { value: "Germany", display: "countries.Germany", symbol: "DE" },
    { value: "Ghana", display: "countries.Ghana", symbol: "GH" },
    { value: "Gibraltar", display: "countries.Gibraltar", symbol: "GI" },
    { value: "Greece", display: "countries.Greece", symbol: "GR" },
    { value: "Greenland", display: "countries.Greenland", symbol: "GL" },
    { value: "Grenada", display: "countries.Grenada", symbol: "GD" },
    { value: "Guam", display: "countries.Guam", symbol: "GU" },
    { value: "Guatemala", display: "countries.Guatemala", symbol: "GT" },
    { value: "Guernsey", display: "countries.Guernsey", symbol: "GG" },
    { value: "Guinea", display: "countries.Guinea", symbol: "GN" },
    { value: "Guinea Bissau", display: "countries.GuineaBissau", symbol: "GW" },
    { value: "Guyana", display: "countries.Guyana", symbol: "GY" },
    { value: "Haiti", display: "countries.Haiti", symbol: "HT" },
    { value: "Honduras", display: "countries.Honduras", symbol: "HN" },
    { value: "Hong Kong", display: "countries.HongKong", symbol: "HK" },
    { value: "Hungary", display: "countries.Hungary", symbol: "HU" },
    { value: "Iceland", display: "countries.Iceland", symbol: "IS" },
    { value: "India", display: "countries.India", symbol: "IN" },
    { value: "Indonesia", display: "countries.Indonesia", symbol: "ID" },
    { value: "Iran", display: "countries.Iran", symbol: "IR" },
    { value: "Iraq", display: "countries.Iraq", symbol: "IQ" },
    { value: "Ireland", display: "countries.Ireland", symbol: "IE" },
    { value: "Isle of Man", display: "countries.IsleofMan", symbol: "IM" },
    { value: "Israel", display: "countries.Israel", symbol: "IL" },
    { value: "Italy", display: "countries.Italy", symbol: "IT" },
    { value: "Jamaica", display: "countries.Jamaica", symbol: "JM" },
    { value: "Japan", display: "countries.Japan", symbol: "JP" },
    { value: "Jersey", display: "countries.Jersey", symbol: "JE" },
    { value: "Jordan", display: "countries.Jordan", symbol: "JO" },
    { value: "Kazakhstan", display: "countries.Kazakhstan", symbol: "KZ" },
    { value: "Kenya", display: "countries.Kenya", symbol: "KE" },
    { value: "Kuwait", display: "countries.Kuwait", symbol: "KW" },
    {
      value: "Kyrgyz Republic",
      display: "countries.KyrgyzRepublic",
      symbol: "KG",
    },
    { value: "Laos", display: "countries.Laos", symbol: "LA" },
    { value: "Latvia", display: "countries.Latvia", symbol: "LV" },
    { value: "Lebanon", display: "countries.Lebanon", symbol: "LB" },
    { value: "Lesotho", display: "countries.Lesotho", symbol: "LS" },
    { value: "Liberia", display: "countries.Liberia", symbol: "LR" },
    { value: "Libya", display: "countries.Libya", symbol: "LY" },
    {
      value: "Liechtenstein",
      display: "countries.Liechtenstein",
      symbol: "LI",
    },
    { value: "Lithuania", display: "countries.Lithuania", symbol: "LT" },
    { value: "Luxembourg", display: "countries.Luxembourg", symbol: "LU" },
    { value: "Macau", display: "countries.Macau", symbol: "MO" },
    { value: "Macedonia", display: "countries.Macedonia", symbol: "MA" },
    { value: "Madagascar", display: "countries.Madagascar", symbol: "MG" },
    { value: "Malawi", display: "countries.Malawi", symbol: "MW" },
    { value: "Malaysia", display: "countries.Malaysia", symbol: "MY" },
    { value: "Maldives", display: "countries.Maldives", symbol: "MV" },
    { value: "Mali", display: "countries.Mali", symbol: "ML" },
    { value: "Malta", display: "countries.Malta", symbol: "MT" },
    { value: "Mauritania", display: "countries.Mauritania", symbol: "MR" },
    { value: "Mauritius", display: "countries.Mauritius", symbol: "MU" },
    { value: "Mexico", display: "countries.Mexico", symbol: "MX" },
    { value: "Moldova", display: "countries.Moldova", symbol: "MD" },
    { value: "Monaco", display: "countries.Monaco", symbol: "MC" },
    { value: "Mongolia", display: "countries.Mongolia", symbol: "MN" },
    { value: "Montenegro", display: "countries.Montenegro", symbol: "ME" },
    { value: "Montserrat", display: "countries.Montserrat", symbol: "MS" },
    { value: "Morocco", display: "countries.Morocco", symbol: "MA" },
    { value: "Mozambique", display: "countries.Mozambique", symbol: "MZ" },
    { value: "Namibia", display: "countries.Namibia", symbol: "NA" },
    { value: "Nepal", display: "countries.Nepal", symbol: "NP" },
    { value: "Netherlands", display: "countries.Netherlands", symbol: "NL" },
    {
      value: "Netherlands Antilles",
      display: "countries.NetherlandsAntilles",
      symbol: "NL",
    },
    { value: "New Caledonia", display: "countries.NewCaledonia", symbol: "NC" },
    { value: "New Zealand", display: "countries.NewZealand", symbol: "NZ" },
    { value: "Nicaragua", display: "countries.Nicaragua", symbol: "NI" },
    { value: "Niger", display: "countries.Niger", symbol: "NE" },
    { value: "Nigeria", display: "countries.Nigeria", symbol: "NG" },
    { value: "Norway", display: "countries.Norway", symbol: "NO" },
    { value: "Oman", display: "countries.Oman", symbol: "OM" },
    { value: "Pakistan", display: "countries.Pakistan", symbol: "PK" },
    { value: "Palestine", display: "countries.Palestine", symbol: "PL" },
    { value: "Panama", display: "countries.Panama", symbol: "PA" },
    {
      value: "Papua New Guinea",
      display: "countries.PapuaNewGuinea",
      symbol: "PG",
    },
    { value: "Paraguay", display: "countries.Paraguay", symbol: "PY" },
    { value: "Peru", display: "countries.Peru", symbol: "PE" },
    { value: "Philippines", display: "countries.Philippines", symbol: "PH" },
    { value: "Poland", display: "countries.Poland", symbol: "PL" },
    { value: "Portugal", display: "countries.Portugal", symbol: "PT" },
    { value: "Puerto Rico", display: "countries.PuertoRico", symbol: "PR" },
    { value: "Qatar", display: "countries.Qatar", symbol: "QA" },
    { value: "Reunion", display: "countries.Reunion", symbol: "RE" },
    { value: "Romania", display: "countries.Romania", symbol: "RO" },
    { value: "Russia", display: "countries.Russia", symbol: "RU" },
    { value: "Rwanda", display: "countries.Rwanda", symbol: "NRWL" },
    {
      value: "Saint Pierre & Miquelon",
      display: "countries.SaintPierreMiquelon",
      symbol: "PM",
    },
    { value: "Samoa", display: "countries.Samoa", symbol: "WS" },
    { value: "San Marino", display: "countries.SanMarino", symbol: "SM" },
    // { value: "Satellite", display: "countries.Satellite", symbol: "NL" },
    { value: "Saudi Arabia", display: "countries.SaudiArabia", symbol: "SA" },
    { value: "Senegal", display: "countries.Senegal", symbol: "SN" },
    { value: "Serbia", display: "countries.Serbia", symbol: "RS" },
    { value: "Seychelles", display: "countries.Seychelles", symbol: "SC" },
    { value: "Sierra Leone", display: "countries.SierraLeone", symbol: "SL" },
    { value: "Singapore", display: "countries.Singapore", symbol: "SG" },
    { value: "Slovakia", display: "countries.Slovakia", symbol: "SK" },
    { value: "Slovenia", display: "countries.Slovenia", symbol: "SI" },
    { value: "South Africa", display: "countries.SouthAfrica", symbol: "ZA" },
    { value: "South Korea", display: "countries.SouthKorea", symbol: "KR" },
    { value: "Spain", display: "countries.Spain", symbol: "ES" },
    { value: "Sri Lanka", display: "countries.SriLanka", symbol: "LK" },
    {
      value: "St Kitts & Nevis",
      display: "countries.StKittsNevis",
      symbol: "SC",
    },
    // { value: "St Lucia", display: "countries.StLucia", symbol: "SC"  },
    // { value: "St Vincent", display: "countries.StVincent", symbol: "SC"  },
    { value: "Sudan", display: "countries.Sudan", symbol: "SD" },
    { value: "Suriname", display: "countries.Suriname", symbol: "SR" },
    // { value: "Swaziland", display: "countries.Swaziland", symbol: "SC"  },
    { value: "Sweden", display: "countries.Sweden", symbol: "SE" },
    { value: "Switzerland", display: "countries.Switzerland", symbol: "CH" },
    { value: "Syria", display: "countries.Syria", symbol: "SY" },
    { value: "Taiwan", display: "countries.Taiwan", symbol: "TW" },
    { value: "Tajikistan", display: "countries.Tajikistan", symbol: "TJ" },
    { value: "Tanzania", display: "countries.Tanzania", symbol: "TZ" },
    { value: "Thailand", display: "countries.Thailand", symbol: "TH" },
    { value: "Timor L'Este", display: "countries.TimorLEste", symbol: "TL" },
    { value: "Togo", display: "countries.Togo", symbol: "TG" },
    { value: "Tonga", display: "countries.Tonga", symbol: "TO" },
    {
      value: "Trinidad & Tobago",
      display: "countries.TrinidadTobago",
      symbol: "TT",
    },
    { value: "Tunisia", display: "countries.Tunisia", symbol: "TN" },
    { value: "Turkey", display: "countries.Turkey", symbol: "TR" },
    { value: "Turkmenistan", display: "countries.Turkmenistan", symbol: "TM" },
    { value: "Turks & Caicos", display: "countries.TurksCaicos", symbol: "TC" },
    { value: "Uganda", display: "countries.Uganda", symbol: "UG" },
    { value: "Ukraine", display: "countries.Ukraine", symbol: "UA" },
    {
      value: "United Arab Emirates",
      display: "countries.UnitedArabEmirates",
      symbol: "AE",
    },
    {
      value: "United Kingdom",
      display: "countries.UnitedKingdom",
      symbol: "GB",
    },
    { value: "Uruguay", display: "countries.Uruguay", symbol: "UY" },
    { value: "Uzbekistan", display: "countries.Uzbekistan", symbol: "UZ" },
    { value: "Venezuela", display: "countries.Venezuela", symbol: "VE" },
    { value: "Vietnam", display: "countries.Vietnam", symbol: "VN" },
    {
      value: "Virgin Islands (US)",
      display: "countries.VirginIslandsUS",
      symbol: "VI",
    },
    { value: "Yemen", display: "countries.Yemen", symbol: "YE" },
    { value: "Zambia", display: "countries.Zambia", symbol: "ZM" },
    { value: "Zimbabwe", display: "countries.Zimbabwe", symbol: "ZW" },
  ].sort((country1, country2) => {
    return country1.value.localeCompare(country2.value);
  });
}
