# Name of workflow as seen in Github actions tab
name: staging-build-and-deploy
# Run workflow only on push to staging branch.
on:
  push:
    branches:
      - staging
jobs:
  # To build the project
  build-nefentus-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Installing dependencies
        run: npm install
      - name: Create .env file
        run: |
          echo "${{ secrets.DOTENV_STAGING }}" > .env.staging
          export NODE_OPTIONS="--max_old_space_size=4096"
      - name: Building project
        run: CI=false npm run build:staging
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to S3 bucket
        run: aws s3 sync ./dist/ s3://staging.nefentus.com
